### ISSUE TITLE
Right to left?

### ISSUE THREAD

**Issue by nashamri** [justincy/d3-pedigree-examples#13]
Hello @justincy and thank you for your amazing work on this project.

I have a question (possibly a feature request :smile: ), how hard will it be to let the tree grow from right to left? as oppose to the way it is growing now (from left to right).

**Comment by justincy** [comment]
@nashamri The third note in the README addresses this issue. It explains how the ancestral tree is configured to display left to right and how the descendants tree is configured to display right to left.

**Comment by nashamri** [comment]
Oh :smile: my bad, thanks again :+1:
