### ISSUE TITLE
How can i make it vertical (top to bottom) rather than horizontal?

### ISSUE THREAD

**Issue by m-adil** [justincy/d3-pedigree-examples#16]
How can i alter to make it vertical i.e. top to bottom rather than horizontal chart? I'm starting from one ancestor and have all children below. 

I'm using [this example i.e. Ancestors & Defendants](http://justincy.github.io/d3-pedigree-examples/descendants.html).

**Comment by justincy** [comment]
My response in this issue explains how to do it: https://github.com/justincy/d3-pedigree-examples/issues/10

**Comment by m-adil** [comment]
thanks for quick response @justincy

**Comment by m-adil** [comment]
@justincy can you or someone please provide an example/link for top to bottom pedigree? I actually got the time today to work on that module again but it doesn't seem so simple as its stated in [your comment](https://github.com/justincy/d3-pedigree-examples/issues/10#issuecomment-218454508) and the third note in the readme. I tried converting [this example](http://justincy.github.io/d3-pedigree-examples/descendants.html) to vertical pedigree following your guide and finally I got top to bottom structure as per my requirements but still the links between the nodes aren't perfect.

I think it will be good if we can add a new issue to create a top-bottom example when possible.

**Comment by justincy** [comment]
Good idea. https://github.com/justincy/d3-pedigree-examples/issues/17

**Comment by m-adil** [comment]
Thanks, I really appreciate.

**Comment by encrayan** [comment]
Any news on this

**Comment by justincy** [comment]
Nope. I haven't done it yet.
