### ISSUE TITLE
Text wrap issue in transitions.html

### ISSUE THREAD

**Issue by Naveencheekoti** [justincy/d3-pedigree-examples#19]
In transitions.html, textwrap functionality is not added.If text is long, what changes are required and where to change in my code.Can you send modified html link or page.
![textwrap](https://user-images.githubusercontent.com/23651242/52423762-c70c5c00-2b1e-11e9-9921-e0bdb1390f6b.PNG)

**Comment by justincy** [comment]
You can look at basic-long-names.html to see how it uses d3plus to enable text wrapping.
