### ISSUE TITLE
Support for multiple interconnections of different branches?

### ISSUE THREAD

**Issue by jslegers** [justincy/d3-pedigree-examples#3]
How's support for multiple interconnections between different branches? I'm looking for a flexible way to display the output of a [GEDCOM ](https://en.wikipedia.org/wiki/GEDCOM)), which is the standard data model for geneology that supports multiple interconnections between different branches of an ancestor tree.

One example would be a case where two sisters of one family marry two brothers of another family. This is the case for a distant relative of mine, sometime in the 17th century, as you can see in the screenshots (of my family tree in [MyHeritage.com](http://www.myheritage.com/)) below.

From the brothers' perspective:
![Brothers](http://i61.tinypic.com/2mi5kz6.png)

From the sisters' perspective:
![Sisters](http://i61.tinypic.com/2vte4r6.png)

A more complicated example would be when a greatgrandfather of a man is the mother-in-law of the grandmother of his wife (or her sister). Something like that too occurs among my 18th century ancestors, but it's a bit more difficult to provide a suitable screenshot.

Is there a way to make this kind of connections with your library without duplicating one or more persons or do you plan on supporting this feature in the future?

**Comment by justincy** [comment]
Thanks for the question. I just added a note at the bottom of the readme that discusses pedigree collapse.
