### ISSUE TITLE
Showing the full tree

### ISSUE THREAD

**Issue by varghesep** [justincy/d3-pedigree-examples#4]
Thanks for those examples. They are very good.

I thought I can use **Family Tree Maker** or **Family Search** to build my family tree. However, when I look at my family history, there are complex relations like common ancestors and cousin marriages etc... I also don't find a software that shows the full picture of my family and my wife's family where I can find the common ancestor. Am I missing anything with the Family Tree Maker or Family Search?

I played with **dagre** and **d3**, but **dagre** does not support ranking. So, it is hard to draw the brothers in the same generation line as an example.

Have you tried presenting the brothers, sisters and wives in the tree and show their ancestors too so the common ancestor can be found? Please see the image that I have attached.

![ft](https://cloud.githubusercontent.com/assets/12233474/9831892/4ef8faea-592e-11e5-9c92-7e0df5fdf63c.png)

**Comment by justincy** [comment]
Doing that in D3 would be a lot of work. Instead, I recommend [Charting Companion](https://progenygenealogy.com/products/family-tree-charts.aspx) from [Progeny Genealogy](https://progenygenealogy.com/). I use Charting Companion for generating advanced charts. I've been very pleased with it.
