### ISSUE TITLE
Marriage relationships in pedigree

### ISSUE THREAD

**Issue by evascaz** [justincy/d3-pedigree-examples#5]
How would I add nodes in your code to show a marriage relationship ?

**Comment by justincy** [comment]
That depends on how you want it to look. Could you give an example?

**Comment by jtrancas** [comment]
I'd like to have this functionality as well, it could be nice if a marriage could be displayed somehow and child nodes would descend from that marriage.

**Comment by justincy** [comment]
Could you create a wireframe that demonstrates how you would want to display marriages?

**Comment by jtrancas** [comment]
This could be a good representation: ![Genealogy tree](http://i.stack.imgur.com/MUE4z.png)

Do you think that's possible? I'm quite new to D3, and I'd be really interested on using D3 Pedigree.

**Comment by justincy** [comment]
D3 is good at displaying trees but it isn't good at displaying graphs. As mentioned in the last note in the Readme, I recommend taking a look at [dagre](https://github.com/cpettitt/dagre) and [dagre-d3](https://github.com/cpettitt/dagre-d3).
