### ISSUE TITLE
Missing html tags

### ISSUE THREAD

**Issue by ilbonte** [justincy/d3-pedigree-examples#6]
In your examples `<head>` tag is missing. You should put `<style>` there. 
You also need to close using the `</body>` the body

**Comment by justincy** [comment]
I followed the convention of the [examples](https://github.com/mbostock/d3/wiki/Gallery) available on [d3js.org](http://d3js.org/), as you can see here: http://bl.ocks.org/mbostock/4062006#index.html

**Comment by ilbonte** [comment]
Didn't know that... Thanks for the clarification!
