### ISSUE TITLE
How to use IBD relation ship PI_HAt value to plot the pedigree plot

### ISSUE THREAD

**Issue by gpcr** [justincy/d3-pedigree-examples#7]
@justincy  : Thanks for nice Pedigree plot. 
I have several samples with their relationship determined by IBD and we have information with pairs of individuals with IBD PHT scores For example input data: 
Sample1, Sample2, 0.25
Sample1, Sample3, 0.125
....
How to use your tool to get the pedigree plot

Say: 
1. Identical twins, and duplicates, are 100% identical by descent (Pihat 1.0)
2. First-degree relatives are 50% IBD (Pihat 0.5)
3. Second-degree relatives are 25% IBD (Pihat 0.25)
4. Third-degree relatives are 12.5% equal IBD (Pihat 0.125)

**Comment by justincy** [comment]
Could you show me an example of how those values would be used to change the pedigree? Do you want to change the position or the color or something else?

**Comment by gpcr** [comment]
http://www.sciencedirect.com/science/article/pii/S0002929714004273

Table 1 expains the ibd values to relations:
Familial Relationship   IBD
Parental    0  
Full-sibling    0.25  
Half-sibling, avuncular, and grandparental  0.5 
First-cousin, great-grandparental, great-avuncular, and half-avuncular  0.75  
Distantly related   varies
Unrelated (includes relationships beyond the third degree)  1

**Comment by justincy** [comment]
@gpcr Thanks. What is it that you need help with? Are you trying to generate a pedigree based on IBD values?

**Comment by gpcr** [comment]
Yes, how to use IBDs to get the pedigre plots

**Comment by justincy** [comment]
Sorry but I don't know how to interpret IBD values, plus it's out of the scope of this repository. You linked to a paper about it. You can use that paper to generate data in the format used by the examples: https://github.com/justincy/d3-pedigree-examples/tree/gh-pages/data
