### ISSUE TITLE
What if a child has 3 step dads

### ISSUE THREAD

**Issue by dagarwal82** [justincy/d3-pedigree-examples#9]
Multiple parent relationship. Currently it duplicates the child. Is it possible to show child only once if it has multiple parents.

**Comment by justincy** [comment]
I don't entirely understand. Could you share an example? I a screenshot of diagram would be best.

**Comment by dagarwal82** [comment]
![1](https://cloud.githubusercontent.com/assets/1272570/13882553/513f5d46-ecfc-11e5-842b-35a21da1b3c1.png)

**Comment by justincy** [comment]
D3 is good at displaying trees but it isn't good at displaying graphs. As mentioned in the last note in the Readme, I recommend taking a look at [dagre](https://github.com/cpettitt/dagre) and [dagre-d3](https://github.com/cpettitt/dagre-d3).

**Comment by dagarwal82** [comment]
Yes. True. I am using dagre now But I really wish If I could use something
more functional. I want the layout as shown in the last attachment.

On Fri, Mar 18, 2016 at 11:29 AM, Justin notifications@github.com wrote:

> D3 is good at displaying trees but it isn't good at displaying graphs. As
> mentioned in the last note in the Readme, I recommend taking a look at
> dagre https://github.com/cpettitt/dagre and dagre-d3
> https://github.com/cpettitt/dagre-d3.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/justincy/d3-pedigree-examples/issues/9#issuecomment-198409512

## 

Deepak Agarwal
9501190044
